### ISSUE TITLE
Exception NoSuchFieldException on Android 9

### ISSUE THREAD

**Issue by Tetraquark** [icerockdev/moko-socket-io#4]
After creating an object of the Socket class, each time I get NoSuchFieldException with stacktrace on an Android 9 device:

```
W/System.err: java.lang.NoSuchFieldException: No field streamHandlers in class Ljava/net/URL; (declaration of 'java.net.URL' appears in /apex/com.android.runtime/javalib/core-oj.jar)
        at java.lang.Class.getDeclaredField(Native Method)
        at dev.icerock.moko.socket.Socket.addURLProtocols(Socket.kt:95)
        at dev.icerock.moko.socket.Socket.<init>(Socket.kt:29)
        at com.snow4unet.snowtinder.chatdomain.di.SocketFactory.createSocket(SocketFactory.kt:17)
        at com.snow4unet.snowtinder.chatdomain.repository.SocketRepository.getSocket(SocketRepository.kt:24)
```

**Comment by TomWayne98** [comment]
I have the same problem. Any update on this?

**Comment by Tetraquark** [comment]
Unfortunately, there are no updates yet

**Comment by ciprig** [comment]
That's cause by `addURLProtocols()` method, not sure why is needed? also running from jvm integration test fail because of that

**Comment by Alex009** [comment]
we remove this method at all
